# Generated by Django 4.2.7 on 2024-05-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
